In [1]:
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import pandas as pd
import time

## Twitch Stats Scrape

In [2]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=True)

url = 'https://twitchtracker.com/games/138585'

response = requests.get(url)

soup = bs(response.text, 'html.parser')

In [3]:
results = soup.find_all('tr')[1:28]
print(len(results))

27

In [4]:
results

[<tr>
 <td data-order="2016-12-01">
 <span class="to-monthyear">2016-12-01</span>
 </td>
 <td><span class="to-number">67629</span></td>
 <td><span class="to-number">279</span></td>
 <td><span class="to-number">225057</span></td>
 <td><span class="to-number">694</span></td>
 <td><span class="to-number">50110767</span></td>
 </tr>, <tr>
 <td data-order="2017-01-01">
 <span class="to-monthyear">2017-01-01</span>
 </td>
 <td><span class="to-number">50758</span></td>
 <td><span class="to-number">242</span></td>
 <td><span class="to-number">100411</span></td>
 <td><span class="to-number">418</span></td>
 <td><span class="to-number">37610475</span></td>
 </tr>, <tr>
 <td data-order="2017-02-01">
 <span class="to-monthyear">2017-02-01</span>
 </td>
 <td><span class="to-number">49671</span></td>
 <td><span class="to-number">222</span></td>
 <td><span class="to-number">139945</span></td>
 <td><span class="to-number">367</span></td>
 <td><span class="to-number">33354988</span></td>
 </tr>, <tr>
 <td data-order="2017-03-01">
 <span class="to-monthyear">2017-03-01</span>
 </td>
 <td><span class="to-number">52111</span></td>
 <td><span class="to-number">227</span></td>
 <td><span class="to-number">241636</span></td>
 <td><span class="to-number">387</span></td>
 <td><span class="to-number">38748339</span></td>
 </tr>, <tr>
 <td data-order="2017-04-01">
 <span class="to-monthyear">2017-04-01</span>
 </td>
 <td><span class="to-number">74146</span></td>
 <td><span class="to-number">308</span></td>
 <td><span class="to-number">277440</span></td>
 <td><span class="to-number">840</span></td>
 <td><span class="to-number">53100504</span></td>
 </tr>, <tr>
 <td data-order="2017-05-01">
 <span class="to-monthyear">2017-05-01</span>
 </td>
 <td><span class="to-number">53461</span></td>
 <td><span class="to-number">248</span></td>
 <td><span class="to-number">127148</span></td>
 <td><span class="to-number">414</span></td>
 <td><span class="to-number">38755685</span></td>
 </tr>, <tr>
 <td data-order="2017-06-01">
 <span class="to-monthyear">2017-06-01</span>
 </td>
 <td><span class="to-number">39147</span></td>
 <td><span class="to-number">203</span></td>
 <td><span class="to-number">86314</span></td>
 <td><span class="to-number">335</span></td>
 <td><span class="to-number">28157541</span></td>
 </tr>, <tr>
 <td data-order="2017-07-01">
 <span class="to-monthyear">2017-07-01</span>
 </td>
 <td><span class="to-number">36336</span></td>
 <td><span class="to-number">218</span></td>
 <td><span class="to-number">141328</span></td>
 <td><span class="to-number">352</span></td>
 <td><span class="to-number">27005273</span></td>
 </tr>, <tr>
 <td data-order="2017-08-01">
 <span class="to-monthyear">2017-08-01</span>
 </td>
 <td><span class="to-number">58124</span></td>
 <td><span class="to-number">301</span></td>
 <td><span class="to-number">212477</span></td>
 <td><span class="to-number">782</span></td>
 <td><span class="to-number">43181329</span></td>
 </tr>, <tr>
 <td data-order="2017-09-01">
 <span class="to-monthyear">2017-09-01</span>
 </td>
 <td><span class="to-number">53134</span></td>
 <td><span class="to-number">258</span></td>
 <td><span class="to-number">125383</span></td>
 <td><span class="to-number">408</span></td>
 <td><span class="to-number">38247580</span></td>
 </tr>, <tr>
 <td data-order="2017-10-01">
 <span class="to-monthyear">2017-10-01</span>
 </td>
 <td><span class="to-number">44681</span></td>
 <td><span class="to-number">237</span></td>
 <td><span class="to-number">214855</span></td>
 <td><span class="to-number">446</span></td>
 <td><span class="to-number">33237807</span></td>
 </tr>, <tr>
 <td data-order="2017-11-01">
 <span class="to-monthyear">2017-11-01</span>
 </td>
 <td><span class="to-number">38232</span></td>
 <td><span class="to-number">261</span></td>
 <td><span class="to-number">139978</span></td>
 <td><span class="to-number">402</span></td>
 <td><span class="to-number">27489354</span></td>
 </tr>, <tr>
 <td data-order="2017-12-01">
 <span class="to-monthyear">2017-12-01</span>
 </td>
 <td><span class="to-number">58016</span></td>
 <td><span class="to-number">373</span></td>
 <td><span class="to-number">205486</span></td>
 <td><span class="to-number">1536</span></td>
 <td><span class="to-number">43149756</span></td>
 </tr>, <tr>
 <td data-order="2018-01-01">
 <span class="to-monthyear">2018-01-01</span>
 </td>
 <td><span class="to-number">47129</span></td>
 <td><span class="to-number">324</span></td>
 <td><span class="to-number">292119</span></td>
 <td><span class="to-number">488</span></td>
 <td><span class="to-number">35055905</span></td>
 </tr>, <tr>
 <td data-order="2018-02-01">
 <span class="to-monthyear">2018-02-01</span>
 </td>
 <td><span class="to-number">41630</span></td>
 <td><span class="to-number">283</span></td>
 <td><span class="to-number">91718</span></td>
 <td><span class="to-number">449</span></td>
 <td><span class="to-number">27913413</span></td>
 </tr>, <tr>
 <td data-order="2018-03-01">
 <span class="to-monthyear">2018-03-01</span>
 </td>
 <td><span class="to-number">37770</span></td>
 <td><span class="to-number">255</span></td>
 <td><span class="to-number">155985</span></td>
 <td><span class="to-number">402</span></td>
 <td><span class="to-number">28101264</span></td>
 </tr>, <tr>
 <td data-order="2018-04-01">
 <span class="to-monthyear">2018-04-01</span>
 </td>
 <td><span class="to-number">59684</span></td>
 <td><span class="to-number">369</span></td>
 <td><span class="to-number">310315</span></td>
 <td><span class="to-number">2283</span></td>
 <td><span class="to-number">42875888</span></td>
 </tr>, <tr>
 <td data-order="2018-05-01">
 <span class="to-monthyear">2018-05-01</span>
 </td>
 <td><span class="to-number">45363</span></td>
 <td><span class="to-number">273</span></td>
 <td><span class="to-number">96171</span></td>
 <td><span class="to-number">482</span></td>
 <td><span class="to-number">33734286</span></td>
 </tr>, <tr>
 <td data-order="2018-06-01">
 <span class="to-monthyear">2018-06-01</span>
 </td>
 <td><span class="to-number">38390</span></td>
 <td><span class="to-number">239</span></td>
 <td><span class="to-number">101753</span></td>
 <td><span class="to-number">428</span></td>
 <td><span class="to-number">27635045</span></td>
 </tr>, <tr>
 <td data-order="2018-07-01">
 <span class="to-monthyear">2018-07-01</span>
 </td>
 <td><span class="to-number">37434</span></td>
 <td><span class="to-number">240</span></td>
 <td><span class="to-number">113884</span></td>
 <td><span class="to-number">367</span></td>
 <td><span class="to-number">27449880</span></td>
 </tr>, <tr>
 <td data-order="2018-08-01">
 <span class="to-monthyear">2018-08-01</span>
 </td>
 <td><span class="to-number">50805</span></td>
 <td><span class="to-number">313</span></td>
 <td><span class="to-number">252699</span></td>
 <td><span class="to-number">1919</span></td>
 <td><span class="to-number">37748606</span></td>
 </tr>, <tr>
 <td data-order="2018-09-01">
 <span class="to-monthyear">2018-09-01</span>
 </td>
 <td><span class="to-number">33650</span></td>
 <td><span class="to-number">218</span></td>
 <td><span class="to-number">80708</span></td>
 <td><span class="to-number">386</span></td>
 <td><span class="to-number">24207671</span></td>
 </tr>, <tr>
 <td data-order="2018-10-01">
 <span class="to-monthyear">2018-10-01</span>
 </td>
 <td><span class="to-number">29833</span></td>
 <td><span class="to-number">212</span></td>
 <td><span class="to-number">83507</span></td>
 <td><span class="to-number">495</span></td>
 <td><span class="to-number">22154109</span></td>
 </tr>, <tr>
 <td data-order="2018-11-01">
 <span class="to-monthyear">2018-11-01</span>
 </td>
 <td><span class="to-number">27056</span></td>
 <td><span class="to-number">209</span></td>
 <td><span class="to-number">101183</span></td>
 <td><span class="to-number">317</span></td>
 <td><span class="to-number">19480896</span></td>
 </tr>, <tr>
 <td data-order="2018-12-01">
 <span class="to-monthyear">2018-12-01</span>
 </td>
 <td><span class="to-number">41800</span></td>
 <td><span class="to-number">254</span></td>
 <td><span class="to-number">205983</span></td>
 <td><span class="to-number">1176</span></td>
 <td><span class="to-number">31099728</span></td>
 </tr>, <tr>
 <td data-order="2019-01-01">
 <span class="to-monthyear">2019-01-01</span>
 </td>
 <td><span class="to-number">32879</span></td>
 <td><span class="to-number">232</span></td>
 <td><span class="to-number">95473</span></td>
 <td><span class="to-number">375</span></td>
 <td><span class="to-number">24449731</span></td>
 </tr>, <tr>
 <td data-order="2019-02-01">
 <span class="to-monthyear">2019-02-01</span>
 </td>
 <td><span class="to-number">20040</span></td>
 <td><span class="to-number">187</span></td>
 <td><span class="to-number">51171</span></td>
 <td><span class="to-number">297</span></td>
 <td><span class="to-number">11876858</span></td>
 </tr>]

In [5]:
twitch_stats = []

for result in results:
    # Splinter can capture a page's underlying html and use pass it to BeautifulSoup to allow us to scrape the content
    html = browser.html
    soup = bs(html, 'html.parser')
    # Error handling
    try:
        
        month = result.find_all('td')[0].text.strip()
        avg_view = result.find_all('td')[1].text
        avg_chan = result.find_all('td')[2].text
        peak_view = result.find_all('td')[3].text
        peak_chan = result.find_all('td')[4].text
        hours_watch = result.find_all('td')[5].text
        
        twitch_stats.append({"month":month, 
                             "avg_view":avg_view, 
                             "avg_chan":avg_chan, 
                             "peak_view":peak_view, 
                             "peak_chan":peak_chan, 
                             "hours_watch":hours_watch})

            
      
            
    except AttributeError as e:
        print(e)

In [6]:
twitch_stats

[{'month': '2016-12-01',
  'avg_view': '67629',
  'avg_chan': '279',
  'peak_view': '225057',
  'peak_chan': '694',
  'hours_watch': '50110767'},
 {'month': '2017-01-01',
  'avg_view': '50758',
  'avg_chan': '242',
  'peak_view': '100411',
  'peak_chan': '418',
  'hours_watch': '37610475'},
 {'month': '2017-02-01',
  'avg_view': '49671',
  'avg_chan': '222',
  'peak_view': '139945',
  'peak_chan': '367',
  'hours_watch': '33354988'},
 {'month': '2017-03-01',
  'avg_view': '52111',
  'avg_chan': '227',
  'peak_view': '241636',
  'peak_chan': '387',
  'hours_watch': '38748339'},
 {'month': '2017-04-01',
  'avg_view': '74146',
  'avg_chan': '308',
  'peak_view': '277440',
  'peak_chan': '840',
  'hours_watch': '53100504'},
 {'month': '2017-05-01',
  'avg_view': '53461',
  'avg_chan': '248',
  'peak_view': '127148',
  'peak_chan': '414',
  'hours_watch': '38755685'},
 {'month': '2017-06-01',
  'avg_view': '39147',
  'avg_chan': '203',
  'peak_view': '86314',
  'peak_chan': '335',
  'hours_watch': '28157541'},
 {'month': '2017-07-01',
  'avg_view': '36336',
  'avg_chan': '218',
  'peak_view': '141328',
  'peak_chan': '352',
  'hours_watch': '27005273'},
 {'month': '2017-08-01',
  'avg_view': '58124',
  'avg_chan': '301',
  'peak_view': '212477',
  'peak_chan': '782',
  'hours_watch': '43181329'},
 {'month': '2017-09-01',
  'avg_view': '53134',
  'avg_chan': '258',
  'peak_view': '125383',
  'peak_chan': '408',
  'hours_watch': '38247580'},
 {'month': '2017-10-01',
  'avg_view': '44681',
  'avg_chan': '237',
  'peak_view': '214855',
  'peak_chan': '446',
  'hours_watch': '33237807'},
 {'month': '2017-11-01',
  'avg_view': '38232',
  'avg_chan': '261',
  'peak_view': '139978',
  'peak_chan': '402',
  'hours_watch': '27489354'},
 {'month': '2017-12-01',
  'avg_view': '58016',
  'avg_chan': '373',
  'peak_view': '205486',
  'peak_chan': '1536',
  'hours_watch': '43149756'},
 {'month': '2018-01-01',
  'avg_view': '47129',
  'avg_chan': '324',
  'peak_view': '292119',
  'peak_chan': '488',
  'hours_watch': '35055905'},
 {'month': '2018-02-01',
  'avg_view': '41630',
  'avg_chan': '283',
  'peak_view': '91718',
  'peak_chan': '449',
  'hours_watch': '27913413'},
 {'month': '2018-03-01',
  'avg_view': '37770',
  'avg_chan': '255',
  'peak_view': '155985',
  'peak_chan': '402',
  'hours_watch': '28101264'},
 {'month': '2018-04-01',
  'avg_view': '59684',
  'avg_chan': '369',
  'peak_view': '310315',
  'peak_chan': '2283',
  'hours_watch': '42875888'},
 {'month': '2018-05-01',
  'avg_view': '45363',
  'avg_chan': '273',
  'peak_view': '96171',
  'peak_chan': '482',
  'hours_watch': '33734286'},
 {'month': '2018-06-01',
  'avg_view': '38390',
  'avg_chan': '239',
  'peak_view': '101753',
  'peak_chan': '428',
  'hours_watch': '27635045'},
 {'month': '2018-07-01',
  'avg_view': '37434',
  'avg_chan': '240',
  'peak_view': '113884',
  'peak_chan': '367',
  'hours_watch': '27449880'},
 {'month': '2018-08-01',
  'avg_view': '50805',
  'avg_chan': '313',
  'peak_view': '252699',
  'peak_chan': '1919',
  'hours_watch': '37748606'},
 {'month': '2018-09-01',
  'avg_view': '33650',
  'avg_chan': '218',
  'peak_view': '80708',
  'peak_chan': '386',
  'hours_watch': '24207671'},
 {'month': '2018-10-01',
  'avg_view': '29833',
  'avg_chan': '212',
  'peak_view': '83507',
  'peak_chan': '495',
  'hours_watch': '22154109'},
 {'month': '2018-11-01',
  'avg_view': '27056',
  'avg_chan': '209',
  'peak_view': '101183',
  'peak_chan': '317',
  'hours_watch': '19480896'},
 {'month': '2018-12-01',
  'avg_view': '41800',
  'avg_chan': '254',
  'peak_view': '205983',
  'peak_chan': '1176',
  'hours_watch': '31099728'},
 {'month': '2019-01-01',
  'avg_view': '32879',
  'avg_chan': '232',
  'peak_view': '95473',
  'peak_chan': '375',
  'hours_watch': '24449731'},
 {'month': '2019-02-01',
  'avg_view': '20040',
  'avg_chan': '187',
  'peak_view': '51171',
  'peak_chan': '297',
  'hours_watch': '11876858'}]

In [7]:
browser.quit

## Tempo Storm Scrape

In [6]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=True)

url = 'https://tempostorm.com/hearthstone/meta-snapshot/standard/2019-02-18'

browser.visit(url)

In [7]:
time.sleep(2)
html = browser.html
soup = bs(html, 'html.parser')

In [8]:
results = soup.find_all('h3', class_='ng-binding')

In [9]:
tier1 = results[10].text.replace('1. ','')
tier1

'Midrange Hunter'

In [10]:
browser.url

'https://tempostorm.com/hearthstone/meta-snapshot/standard/2019-02-18'

In [11]:
tier_one_decks = []

for x in range(3):   
    time.sleep(2)
    html = browser.html
    soup = bs(html, 'html.parser')
    
    results = soup.find_all('h3', class_='ng-binding')
    tier1 = results[10].text.replace('1. ','')
    
    if tier1 == 'Tier 1':
        tier1 = results[11].text.replace('1. ','')
        
    print(browser.url)
    base_link = browser.url
    print(tier1)
    links_found = soup.find_all('a', class_='big-view-deck-link pull-left ng-binding')
    link = "https://tempostorm.com" + links_found[0]['href']
    
    browser.visit(link)
    print(browser.url)
    time.sleep(2)
    html = browser.html
    soup = bs(html, 'html.parser')
    
    
    results2 = soup.find_all('div', class_='db-deck-card-name ng-binding')
    results2 = set(results2)
    deck_list = []
    for result in results2:
        deck_list.append(result.text)
    
    browser.visit(base_link)
    tier_one_decks.append({"deck":tier1,"deck_list":deck_list ,"date":browser.url.replace('https://tempostorm.com/hearthstone/meta-snapshot/standard/','')})

    time.sleep(2)
    button = browser.find_by_css('.btn-pagination-arrow.m-r-xs')    
    button.click()

https://tempostorm.com/hearthstone/meta-snapshot/standard/2019-02-18
Midrange Hunter
https://tempostorm.com/hearthstone/decks/midrange-hunter-standard-meta-snapshot-feb-18-2019
https://tempostorm.com/hearthstone/meta-snapshot/standard/2019-02-12
Midrange Hunter
https://tempostorm.com/hearthstone/decks/midrange-hunter-standard-meta-snapshot-feb-12-2019
https://tempostorm.com/hearthstone/meta-snapshot/standard/2019-01-27
Subject 9 Hunter
https://tempostorm.com/hearthstone/decks/subject-9-hunter-standard-meta-snapshot-jan-27-2019

In [12]:
browser.quit

In [13]:
tier_one_decks

[{'deck': 'Midrange Hunter',
  'deck_list': ['Dire Mole',
   'Animal Companion',
   "Master's Call",
   'Lifedrinker',
   'Tracking',
   'Crackling Razormaw',
   'Unleash the Hounds',
   'Flanking Strike',
   'Tundra Rhino',
   'Deathstalker Rexxar',
   'Scavenging Hyena',
   'Dire Frenzy',
   'Kill Command',
   'Springpaw',
   "Headhunter's Hatchet",
   'Timber Wolf'],
  'date': '2019-02-18'},
 {'deck': 'Midrange Hunter',
  'deck_list': ['Dire Mole',
   'Animal Companion',
   "Master's Call",
   'Tracking',
   'Crackling Razormaw',
   'Unleash the Hounds',
   'Flanking Strike',
   'Revenge of the Wild',
   'Deathstalker Rexxar',
   'Candleshot',
   'Scavenging Hyena',
   'Dire Frenzy',
   'Kill Command',
   'Springpaw',
   'Tundra Rhino',
   'Timber Wolf'],
  'date': '2019-02-12'},
 {'deck': 'Subject 9 Hunter',
  'deck_list': ['Animal Companion',
   'Flanking Strike',
   'Explosive Trap',
   'Candleshot',
   'Scavenging Hyena',
   "Zul'jin",
   'Lesser Emerald Spellstone',
   'Snake Trap',
   'Deathstalker Rexxar',
   'Dire Frenzy',
   'Wandering Monster',
   'Dire Mole',
   'Crackling Razormaw',
   'Freezing Trap',
   "Hunter's Mark",
   "Master's Call",
   'Springpaw',
   'Tundra Rhino',
   'Subject 9',
   'Venomstrike Trap',
   'Kill Command'],
  'date': '2019-01-27'}]